/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ufjf.dcc025.monitoramentoru.view;

import javax.swing.JLabel;

/**
 *
 * @author arthu
 */
public class MostraCardapio extends javax.swing.JFrame {

    /**
     * Creates new form MostraCardapio
     */
    public MostraCardapio() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelOpcaoPrincipal = new javax.swing.JLabel();
        jLabelOpcaoVegetariana = new javax.swing.JLabel();
        jLabelGuarnicao = new javax.swing.JLabel();
        jLabelMacarrao = new javax.swing.JLabel();
        jLabelArroz = new javax.swing.JLabel();
        jLabelFeijao = new javax.swing.JLabel();
        jLabelSopa = new javax.swing.JLabel();
        jLabelSobremesa = new javax.swing.JLabel();
        jLabelDiaSemana = new javax.swing.JLabel();
        jLabelTurno = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabelRespDiaSemana = new javax.swing.JLabel();
        jLabelRespTurno = new javax.swing.JLabel();
        jLabelRespPrincipal = new javax.swing.JLabel();
        jLabelRespVegetariano = new javax.swing.JLabel();
        jLabelRespGuarnicao = new javax.swing.JLabel();
        jLabelRespMacarrao = new javax.swing.JLabel();
        jLabelRespArroz = new javax.swing.JLabel();
        jLabelRespFeijao = new javax.swing.JLabel();
        jLabelRespSopa = new javax.swing.JLabel();
        jLabelRespSobremesa = new javax.swing.JLabel();
        jButtonOK = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cardápio");

        jLabelOpcaoPrincipal.setFont(new java.awt.Font("Calibri Light", 1, 14)); // NOI18N
        jLabelOpcaoPrincipal.setText("jLabel1");

        jLabelOpcaoVegetariana.setFont(new java.awt.Font("Calibri Light", 1, 14)); // NOI18N
        jLabelOpcaoVegetariana.setText("jLabel2");

        jLabelGuarnicao.setFont(new java.awt.Font("Calibri Light", 1, 14)); // NOI18N
        jLabelGuarnicao.setText("jLabel3");

        jLabelMacarrao.setFont(new java.awt.Font("Calibri Light", 1, 14)); // NOI18N
        jLabelMacarrao.setText("jLabel4");

        jLabelArroz.setFont(new java.awt.Font("Calibri Light", 1, 14)); // NOI18N
        jLabelArroz.setText("jLabel5");

        jLabelFeijao.setFont(new java.awt.Font("Calibri Light", 1, 14)); // NOI18N
        jLabelFeijao.setText("jLabel6");

        jLabelSopa.setFont(new java.awt.Font("Calibri Light", 1, 14)); // NOI18N
        jLabelSopa.setText("jLabel7");

        jLabelSobremesa.setFont(new java.awt.Font("Calibri Light", 1, 14)); // NOI18N
        jLabelSobremesa.setText("jLabel8");

        jLabelDiaSemana.setFont(new java.awt.Font("Calibri Light", 3, 14)); // NOI18N
        jLabelDiaSemana.setText("jLabel9");

        jLabelTurno.setFont(new java.awt.Font("Calibri Light", 3, 14)); // NOI18N
        jLabelTurno.setText("jLabel1");

        jLabel1.setFont(new java.awt.Font("Calibri Light", 2, 20)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Cardápio RU - UFJF");
        jLabel1.setAlignmentY(0.0F);

        jLabelRespDiaSemana.setFont(new java.awt.Font("Calibri Light", 0, 14)); // NOI18N
        jLabelRespDiaSemana.setText("jLabel2");

        jLabelRespTurno.setFont(new java.awt.Font("Calibri Light", 0, 14)); // NOI18N
        jLabelRespTurno.setText("jLabel3");

        jLabelRespPrincipal.setFont(new java.awt.Font("Calibri Light", 0, 14)); // NOI18N
        jLabelRespPrincipal.setText("jLabel2");

        jLabelRespVegetariano.setFont(new java.awt.Font("Calibri Light", 0, 14)); // NOI18N
        jLabelRespVegetariano.setText("jLabel2");

        jLabelRespGuarnicao.setFont(new java.awt.Font("Calibri Light", 0, 14)); // NOI18N
        jLabelRespGuarnicao.setText("jLabel2");

        jLabelRespMacarrao.setFont(new java.awt.Font("Calibri Light", 0, 14)); // NOI18N
        jLabelRespMacarrao.setText("jLabel2");

        jLabelRespArroz.setFont(new java.awt.Font("Calibri Light", 0, 14)); // NOI18N
        jLabelRespArroz.setText("jLabel2");

        jLabelRespFeijao.setFont(new java.awt.Font("Calibri Light", 0, 14)); // NOI18N
        jLabelRespFeijao.setText("jLabel2");

        jLabelRespSopa.setFont(new java.awt.Font("Calibri Light", 0, 14)); // NOI18N
        jLabelRespSopa.setText("jLabel2");

        jLabelRespSobremesa.setFont(new java.awt.Font("Calibri Light", 0, 14)); // NOI18N
        jLabelRespSobremesa.setText("jLabel2");

        jButtonOK.setFont(new java.awt.Font("Calibri Light", 0, 14)); // NOI18N
        jButtonOK.setText("Ok");
        jButtonOK.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonOKMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelDiaSemana, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE)
                                    .addComponent(jLabelTurno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabelOpcaoPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabelOpcaoVegetariana, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabelGuarnicao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(27, 27, 27))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelMacarrao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabelArroz, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabelFeijao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabelSopa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabelSobremesa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelRespSopa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabelRespSobremesa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabelRespFeijao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabelRespArroz, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabelRespMacarrao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelRespGuarnicao, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE)
                                    .addComponent(jLabelRespVegetariano, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabelRespPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabelRespTurno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabelRespDiaSemana, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(52, 52, 52))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(jLabel1)
                        .addGap(13, 13, 13)))
                .addGap(104, 104, 104))
            .addGroup(layout.createSequentialGroup()
                .addGap(169, 169, 169)
                .addComponent(jButtonOK, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel1)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelDiaSemana)
                    .addComponent(jLabelRespDiaSemana))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelTurno)
                    .addComponent(jLabelRespTurno))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelOpcaoPrincipal)
                    .addComponent(jLabelRespPrincipal))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelRespVegetariano)
                    .addComponent(jLabelOpcaoVegetariana))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelRespGuarnicao)
                    .addComponent(jLabelGuarnicao))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelRespMacarrao)
                    .addComponent(jLabelMacarrao))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelRespArroz)
                    .addComponent(jLabelArroz))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelRespFeijao)
                    .addComponent(jLabelFeijao))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelRespSopa)
                    .addComponent(jLabelSopa))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelRespSobremesa)
                    .addComponent(jLabelSobremesa))
                .addGap(27, 27, 27)
                .addComponent(jButtonOK)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonOKMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonOKMouseClicked
        this.setVisible(false);
    }//GEN-LAST:event_jButtonOKMouseClicked

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(MostraCardapio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(MostraCardapio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(MostraCardapio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(MostraCardapio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new MostraCardapio().setVisible(true);
//           jLabel      });
//    }
    


    public void setjLabel2(JLabel jLabel2) {
        this.jLabelRespDiaSemana = jLabel2;
    }

    public JLabel getjLabel3() {
        return jLabelGuarnicao;
    }

    public void setjLabel3(JLabel jLabel3) {
        this.jLabelGuarnicao = jLabel3;
    }

    public JLabel getjLabel4() {
        return jLabelMacarrao;
    }

    public void setjLabel4(JLabel jLabel4) {
        this.jLabelMacarrao = jLabel4;
    }

    public JLabel getjLabel5() {
        return jLabelArroz;
    }

    public void setjLabel5(JLabel jLabel5) {
        this.jLabelArroz = jLabel5;
    }

    public JLabel getjLabel6() {
        return jLabelFeijao;
    }

    public void setjLabel6(JLabel jLabel6) {
        this.jLabelFeijao = jLabel6;
    }

    public JLabel getjLabel7() {
        return jLabelSopa;
    }

    public void setjLabel7(JLabel jLabel7) {
        this.jLabelSopa = jLabel7;
    }

    public JLabel getjLabel8() {
        return jLabelSobremesa;
    }

    public void setjLabel8(JLabel jLabel8) {
        this.jLabelSobremesa = jLabel8;
    }

    public JLabel getjLabel9() {
        return jLabelDiaSemana;
    }

    public void setjLabel9(JLabel jLabel9) {
        this.jLabelDiaSemana = jLabel9;
    }

    public JLabel getjLabelOpcaoPrincipal() {
        return jLabelOpcaoPrincipal;
    }

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(MostraCardapio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(MostraCardapio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(MostraCardapio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(MostraCardapio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new MostraCardapio().setVisible(true);
//            }
//        });
//    }
    public void setjLabelOpcaoPrincipal(JLabel jLabelOpcaoPrincipal) {
        this.jLabelOpcaoPrincipal = jLabelOpcaoPrincipal;
    }    
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonOK;
    private javax.swing.JLabel jLabel1;
    public javax.swing.JLabel jLabelArroz;
    public javax.swing.JLabel jLabelDiaSemana;
    public javax.swing.JLabel jLabelFeijao;
    public javax.swing.JLabel jLabelGuarnicao;
    public javax.swing.JLabel jLabelMacarrao;
    public javax.swing.JLabel jLabelOpcaoPrincipal;
    public javax.swing.JLabel jLabelOpcaoVegetariana;
    public javax.swing.JLabel jLabelRespArroz;
    public javax.swing.JLabel jLabelRespDiaSemana;
    public javax.swing.JLabel jLabelRespFeijao;
    public javax.swing.JLabel jLabelRespGuarnicao;
    public javax.swing.JLabel jLabelRespMacarrao;
    public javax.swing.JLabel jLabelRespPrincipal;
    public javax.swing.JLabel jLabelRespSobremesa;
    public javax.swing.JLabel jLabelRespSopa;
    public javax.swing.JLabel jLabelRespTurno;
    public javax.swing.JLabel jLabelRespVegetariano;
    public javax.swing.JLabel jLabelSobremesa;
    public javax.swing.JLabel jLabelSopa;
    public javax.swing.JLabel jLabelTurno;
    // End of variables declaration//GEN-END:variables
}
