/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ufjf.dcc025.monitoramentoru.view;

import ufjf.dcc025.monitoramentoru.model.MonitorarLotacao;
import ufjf.dcc025.monitoramentoru.model.Usuario;

/**
 *
 * @author Your Name <lucas.esteves@engenharia.ufjf.br>
 */
public class TelaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form TelaPrincipal
     */
//    private Usuario usuario;
    public TelaPrincipal() {
        initComponents();
//        this.usuario = null;
    }

//    public void setUsuario(Usuario usuario) {
//        this.usuario = usuario;
//    }
//    
//    public Usuario getUsuario() {
//        return usuario;
//    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBarTelaPrincipal2 = new javax.swing.JMenuBar();
        jMenuPrincipal2 = new javax.swing.JMenu();
        jMenuItemMonitorarLotacao2 = new javax.swing.JMenuItem();
        jMenuItemCardapio2 = new javax.swing.JMenuItem();
        jMenuItemRegistraHorario = new javax.swing.JMenuItem();
        jMenuItemAgendarHorario = new javax.swing.JMenuItem();
        jMenuItemEticket = new javax.swing.JMenuItem();
        jMenuPerfil = new javax.swing.JMenu();
        jMenuItemEditarPerfil = new javax.swing.JMenuItem();
        jMenuContato = new javax.swing.JMenu();
        jMenuItemContato = new javax.swing.JMenuItem();
        jMenuSair = new javax.swing.JMenu();
        jMenuItemSair = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jMenuPrincipal2.setText("Menu Principal");
        jMenuPrincipal2.setFont(new java.awt.Font("Gill Sans Ultra Bold Condensed", 0, 18)); // NOI18N

        jMenuItemMonitorarLotacao2.setFont(new java.awt.Font("Gill Sans MT", 0, 18)); // NOI18N
        jMenuItemMonitorarLotacao2.setText("Monitorar Lotação");
        jMenuItemMonitorarLotacao2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemMonitorarLotacao2ActionPerformed(evt);
            }
        });
        jMenuPrincipal2.add(jMenuItemMonitorarLotacao2);

        jMenuItemCardapio2.setFont(new java.awt.Font("Gill Sans MT", 0, 18)); // NOI18N
        jMenuItemCardapio2.setText("Cardápio");
        jMenuItemCardapio2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCardapio2ActionPerformed(evt);
            }
        });
        jMenuPrincipal2.add(jMenuItemCardapio2);

        jMenuItemRegistraHorario.setFont(new java.awt.Font("Gill Sans MT", 0, 18)); // NOI18N
        jMenuItemRegistraHorario.setText("Registrar Horários");
        jMenuItemRegistraHorario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemRegistraHorarioActionPerformed(evt);
            }
        });
        jMenuPrincipal2.add(jMenuItemRegistraHorario);

        jMenuItemAgendarHorario.setFont(new java.awt.Font("Gill Sans MT", 0, 18)); // NOI18N
        jMenuItemAgendarHorario.setText("Agendar Horário");
        jMenuItemAgendarHorario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemAgendarHorarioActionPerformed(evt);
            }
        });
        jMenuPrincipal2.add(jMenuItemAgendarHorario);

        jMenuItemEticket.setFont(new java.awt.Font("Gill Sans MT", 0, 18)); // NOI18N
        jMenuItemEticket.setText("e-Ticket");
        jMenuItemEticket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemEticketActionPerformed(evt);
            }
        });
        jMenuPrincipal2.add(jMenuItemEticket);

        jMenuBarTelaPrincipal2.add(jMenuPrincipal2);

        jMenuPerfil.setText("Perfil");
        jMenuPerfil.setFont(new java.awt.Font("Gill Sans Ultra Bold", 0, 14)); // NOI18N

        jMenuItemEditarPerfil.setFont(new java.awt.Font("Gill Sans MT", 0, 18)); // NOI18N
        jMenuItemEditarPerfil.setText("Editar Perfil");
        jMenuItemEditarPerfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemEditarPerfilActionPerformed(evt);
            }
        });
        jMenuPerfil.add(jMenuItemEditarPerfil);

        jMenuBarTelaPrincipal2.add(jMenuPerfil);

        jMenuContato.setText("Contato");
        jMenuContato.setFont(new java.awt.Font("Gill Sans Ultra Bold", 0, 14)); // NOI18N

        jMenuItemContato.setFont(new java.awt.Font("Gill Sans MT", 0, 18)); // NOI18N
        jMenuItemContato.setText("Contato");
        jMenuItemContato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemContatoActionPerformed(evt);
            }
        });
        jMenuContato.add(jMenuItemContato);

        jMenuBarTelaPrincipal2.add(jMenuContato);

        jMenuSair.setText("Sair");
        jMenuSair.setFont(new java.awt.Font("Gill Sans Ultra Bold", 0, 14)); // NOI18N

        jMenuItemSair.setFont(new java.awt.Font("Gill Sans MT", 0, 18)); // NOI18N
        jMenuItemSair.setText("Sair");
        jMenuItemSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemSairActionPerformed(evt);
            }
        });
        jMenuSair.add(jMenuItemSair);

        jMenuBarTelaPrincipal2.add(jMenuSair);

        setJMenuBar(jMenuBarTelaPrincipal2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 350, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 325, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemCardapio2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCardapio2ActionPerformed
        
        TelaCardapio telaCardapio = new TelaCardapio();
        telaCardapio.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_jMenuItemCardapio2ActionPerformed

    private void jMenuItemEticketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemEticketActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItemEticketActionPerformed

    private void jMenuItemEditarPerfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemEditarPerfilActionPerformed
        
        TelaPerfil telaperfil = new TelaPerfil();
        telaperfil.setVisible(true);

    }//GEN-LAST:event_jMenuItemEditarPerfilActionPerformed

    private void jMenuItemRegistraHorarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemRegistraHorarioActionPerformed

        TelaCadastraHorarios telacadastro = new TelaCadastraHorarios();
        telacadastro.setVisible(true);

    }//GEN-LAST:event_jMenuItemRegistraHorarioActionPerformed

    private void jMenuItemAgendarHorarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAgendarHorarioActionPerformed
       
       TelaAgendarRefeicao telarefeicao = new TelaAgendarRefeicao();
       telarefeicao.setVisible(true);
       
    }//GEN-LAST:event_jMenuItemAgendarHorarioActionPerformed

    private void jMenuItemMonitorarLotacao2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemMonitorarLotacao2ActionPerformed
        
        TelaMonitoramento telamonitoramento = new TelaMonitoramento();
        telamonitoramento.setVisible(true);
        
    }//GEN-LAST:event_jMenuItemMonitorarLotacao2ActionPerformed

    private void jMenuItemContatoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemContatoActionPerformed
     TelaContato contato = new TelaContato();
     contato.setVisible(true);
    }//GEN-LAST:event_jMenuItemContatoActionPerformed

    private void jMenuItemSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemSairActionPerformed
        
        this.dispose();
        TelaLogin telalogin = new TelaLogin();
        telalogin.setVisible(true);
        
    }//GEN-LAST:event_jMenuItemSairActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBarTelaPrincipal2;
    private javax.swing.JMenu jMenuContato;
    private javax.swing.JMenuItem jMenuItemAgendarHorario;
    private javax.swing.JMenuItem jMenuItemCardapio2;
    private javax.swing.JMenuItem jMenuItemContato;
    private javax.swing.JMenuItem jMenuItemEditarPerfil;
    private javax.swing.JMenuItem jMenuItemEticket;
    private javax.swing.JMenuItem jMenuItemMonitorarLotacao2;
    private javax.swing.JMenuItem jMenuItemRegistraHorario;
    private javax.swing.JMenuItem jMenuItemSair;
    private javax.swing.JMenu jMenuPerfil;
    private javax.swing.JMenu jMenuPrincipal2;
    private javax.swing.JMenu jMenuSair;
    // End of variables declaration//GEN-END:variables
}
